# Kafka configuration
server:
    port: 8888
spring:
    kafka:
        consumer:
            group-id: demo-loggers # default consumer group for our consumers
            auto-offset-reset: earliest # means that a consumer will start reading from the earliest offset when there is no offset for that consumer
        bootstrap-servers: localhost:9092

# Application properties
demo:
    kafka:
        topic-name: advice-topic
        messages-per-request: 10
